const express = require("express")
const router = express.Router()
const controller = require("../controller/Authen_Y.controller")
const Authorizes = require("../middleware/Authentication_Y")
const loglimit = require("../middleware/Rate_limit_Y")
router.get("/Getall",Authorizes,controller.Getall)
router.post("/create",Authorizes,controller.register)
router.patch("/patch",Authorizes,controller.patch)
router.patch("/deleted",Authorizes,controller.deleted)
router.patch("/changestatus",Authorizes,controller.changeStatus)
router.get("/authorizes",Authorizes,controller.Authorizes)
router.post("/login",loglimit(),controller.login)
router.post("/logout",controller.login)
router.patch("/adminlogout",Authorizes,controller.adminlogout)

module.exports = router